//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int id { get; set; }
        public Nullable<int> IdOrder { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string customerID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
